const chefQuotes = [
  {q: "The only time to eat diet food is while you're waiting for the steak to cook.", c: "Julia Child"},
  {q: "People who love to eat are always the best people.", c: "Julia Child"},
  {q: "The only real stumbling block is fear of failure. In cooking you've got to have a what-the-hell attitude.", c: "Julia Child"},
  {q: "You don't have to cook fancy or complicated masterpieces—just good food from fresh ingredients.", c: "Julia Child"},
  {q: "A recipe has no soul. You, as the cook, must bring soul to the recipe.", c: "Thomas Keller"},
  {q: "Your body is not a temple, it's an amusement park. Enjoy the ride.", c: "Anthony Bourdain"},
  {q: "Good food is very often, even most often, simple food.", c: "Anthony Bourdain"},
  {q: "Context and memory play powerful roles in all the truly great meals in one's life.", c: "Anthony Bourdain"},
  {q: "Cooking is about confidence. The more you cook, the better you get.", c: "Anthony Bourdain"},
  {q: "I think every woman should have a blowtorch.", c: "Julia Child"},
  {q: "Fat gives things flavor.", c: "Julia Child"},
  {q: "In cooking, as in all the arts, simplicity is the sign of perfection.", c: "Curnonsky"},
  {q: "One cannot think well, love well, sleep well, if one has not dined well.", c: "Virginia Woolf"},
  {q: "There is no sincerer love than the love of food.", c: "George Bernard Shaw"},
  {q: "Tell me what you eat, and I will tell you who you are.", c: "Brillat-Savarin"},
  {q: "First we eat, then we do everything else.", c: "M.F.K. Fisher"},
  {q: "Cooking is like painting or writing a song.", c: "Wolfgang Puck"},
  {q: "If you are afraid of butter, use cream.", c: "Julia Child"},
  {q: "Always start out with a larger pot than what you think you need.", c: "Julia Child"},
  {q: "How can a nation be called great if its bread tastes like Kleenex?", c: "Julia Child"},
  {q: "Cooking is one failure after another, and that's how you finally learn.", c: "Julia Child"},
  {q: "No one is born a great cook, one learns by doing.", c: "Julia Child"},
  {q: "Laughter is brightest in the place where the food is.", c: "Irish Proverb"},
  {q: "The discovery of a new dish does more for human happiness than the discovery of a new star.", c: "Brillat-Savarin"},
  {q: "Once you understand the foundations of cooking, really understand it, you become free.", c: "Thomas Keller"},
  {q: "Cooking well doesn't mean cooking fancy.", c: "Julia Child"},
  {q: "After a good dinner one can forgive anybody, even one's own relations.", c: "Oscar Wilde"},
  {q: "We all eat, and it would be a sad waste of opportunity to eat badly.", c: "Anna Thomas"},
  {q: "When baking, follow directions. When cooking, go by your own taste.", c: "Laiko Bahrs"},
  {q: "Food brings people together on many different levels.", c: "Giada De Laurentiis"},
  {q: "This squid is so undercooked I can still hear it telling SpongeBob to fuck off.", c: "Gordon Ramsay"},
  {q: "This lamb is so undercooked, it's following Mary to school.", c: "Gordon Ramsay"},
  {q: "If you want to become a great chef, you have to work with great chefs.", c: "Gordon Ramsay"},
  {q: "I cook with wine, sometimes I even add it to the food.", c: "W.C. Fields"},
  {q: "Salt is born of the purest of parents: the sun and the sea.", c: "Pythagoras"},
  {q: "Fat is flavor.", c: "Samin Nosrat"},
  {q: "Salt enhances flavor. Fat carries flavor. Acid balances flavor. Heat transforms flavor.", c: "Samin Nosrat"},
  {q: "The way you make an omelet reveals your character.", c: "Anthony Bourdain"},
  {q: "Great cooking favors the prepared hands.", c: "Jacques Pépin"},
  {q: "Recipes tell you nothing. Learning techniques is the key.", c: "Tom Colicchio"},
  {q: "Never trust a skinny cook.", c: "Italian Proverb"},
  {q: "Store-bought is fine.", c: "Ina Garten"},
  {q: "How easy is that?", c: "Ina Garten"},
  {q: "If you can't get good ingredients, don't make the dish.", c: "Ina Garten"},
  {q: "Always buy the best butter you can afford.", c: "Ina Garten"},
  {q: "Don't be a recipe slave.", c: "Alton Brown"},
  {q: "Organization will set you free.", c: "Alton Brown"},
  {q: "Pull up a chair. Take a taste. Come join us. Life is so endlessly delicious.", c: "Ruth Reichl"},
  {q: "Mise en place.", c: "Every Chef Ever"},
  {q: "Season as you go.", c: "Jacques Pépin"},
  {q: "Heard!", c: "Every Line Cook Ever"}
];

function getRandomQuote() {
  return chefQuotes[Math.floor(Math.random() * chefQuotes.length)];
}
